### ISSUE TITLE
Prevent layout shifts on the navigation when an item is selected (bold)

### ISSUE THREAD

**Issue by Mogztter** [asciidoctor/asciidoctor-docs-ui#9]
![test](https://user-images.githubusercontent.com/333276/99188641-451e7d80-275d-11eb-94fc-9ff9bbdd4298.gif)

Using a small padding on the right can solve this issue:

![test1](https://user-images.githubusercontent.com/333276/99188645-4e0f4f00-275d-11eb-8412-4581e85ed470.gif)

Arguably, we should also fix this issue upstream: https://gitlab.com/antora/antora-ui-default

What do you think?

**Comment by mojavelinux** [comment]
This is due to the fact that the bold font uses slightly more space than the normal font. While the padding right may fix this particular case, it doesn't actually solve the problem. The bold font will still take up more space and eventually it will cause a layout shift.

One possible solution is to use the -webkit-text-stroke to darken the stroke instead of using the bold font. It doesn't look as nice, but it won't affect the layout.

Another solution is to adjust the letter spacing when applying bold. This can be very difficult to get right and could end up overcompensating and thus causing a layout shift in the other direction.

I'm really not sure what the right answer is. Perhaps we should consult some CSS experts.

Ideally, a bold font won't take up more space than the normal font, but that seems to be the case with Roboto.

**Comment by Mogztter** [comment]
Another technique is to stack a non-visible (with `visibility: hidden`) pseudo-element that has a bold font. The pseudo-element will take the width required but won't be visible. In other words, it will reserve the space required to display the text with a bold font.

```css
.menu.fix .menu-link::after {
  content: attr(data-text);
  content: attr(data-text) / "";
  height: 0;
  visibility: hidden;
  overflow: hidden;
  user-select: none;
  pointer-events: none;
  font-weight: var(--bold);

  @media speech {
    display: none;
  }
}
```

https://css-tricks.com/bold-on-hover-without-the-layout-shift/
